export type Home={id:string;name:string;area:string;rent:string;deposit:string;maintenance:string;size:string;floor:string;date:string;notes:string;checks:Record<string,boolean>;ratings:Record<string,number>};
export type Item={id:string;label:string;hint:string};export type Section={id:string;title:string;items:Item[]};
export const sections:Section[]=[
{id:'entry',title:'First look & entry',items:[{id:'road',label:'Approach road and building entry',hint:'Road, lighting, gate and cleanliness'},{id:'lobby',label:'Lobby, lifts and common areas',hint:'Lift condition, backup, wait time'},{id:'noise',label:'Noise, smell and natural light',hint:'Check with windows open and closed'}]},
{id:'inside',title:'Inside the home',items:[{id:'walls',label:'Walls, ceilings and dampness',hint:'Cracks, bubbling paint or seepage'},{id:'doors',label:'Flooring, doors, windows and locks',hint:'Loose tiles, seals and mosquito mesh'},{id:'water',label:'Water pressure and drainage',hint:'Test taps, shower, flush, hot water'},{id:'power',label:'Switches, sockets and power backup',hint:'Test sockets; confirm backup coverage'},{id:'kitchen',label:'Kitchen, cabinets and exhaust',hint:'Leaks, storage, chimney, appliance points'},{id:'bath',label:'Bathrooms and ventilation',hint:'Fittings, exhaust, smell and seepage'},{id:'storage',label:'Storage and usable room sizes',hint:'Wardrobes, bed and appliance fit'},{id:'balcony',label:'Balcony, view and ventilation',hint:'Safety rails, privacy, drainage and sun'}]},
{id:'society',title:'Building & society',items:[{id:'security',label:'Security and visitor entry',hint:'Guards, CCTV and delivery process'},{id:'parking',label:'Parking and building access',hint:'Dedicated slot and visitor parking'},{id:'amenities',label:'Amenities and actual condition',hint:'Check what is open and maintained'},{id:'child',label:'Child safety and family needs',hint:'Balcony rails, play area, nearby shops'},{id:'upkeep',label:'Society upkeep and rules',hint:'Waste, pets, move-in fees, restrictions'}]},
{id:'location',title:'Location & commute',items:[{id:'office',label:'Office commute at peak hour',hint:'Estimate route to Sector 144 in rush hour'},{id:'metro',label:'Metro, cabs and autos nearby',hint:'Check real walking distance and availability'},{id:'daily',label:'Groceries, pharmacy and food delivery',hint:'Daily needs, clinic, school, deliveries'},{id:'traffic',label:'Traffic, construction and waterlogging',hint:'Ask residents; check nearby construction'}]},
{id:'paperwork',title:'Owner & paperwork',items:[{id:'owner',label:'Owner identity and authority',hint:'Confirm the person can legally rent it'},{id:'agreement',label:'Agreement, lock-in and notice period',hint:'Clarify renewal and exit terms in writing'},{id:'refund',label:'Deposit refund and deductions',hint:'Agree refund timeline and deductions'},{id:'handover',label:'Inventory, repairs and handover',hint:'Photograph damage and meter readings'}]}];
export const total=sections.reduce((n,s)=>n+s.items.length,0);const key='homesearch.v1';export const blank=():Home=>({id:crypto.randomUUID(),name:'',area:'',rent:'',deposit:'',maintenance:'',size:'',floor:'',date:new Date().toISOString().slice(0,10),notes:'',checks:{},ratings:{}});export const load=():Home[]=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return[]}};
